# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
orbs:
  ghpr: narrativescience/ghpr@1.1.2
jobs:
  deploy-production:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy over SSH
          command: ssh -p $SSH_PORT $SSH_USERNAME@$SSH_HOST "sh /script/trycd-prod.sh";
  deploy-testing:
    machine:
      enabled: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Deploy over SSH
          command: |
            echo "$GITHUB_PR_BASE_BRANCH - 1"
            scp -P $SSH_PORT -r ~/app/ $SSH_USERNAME@$SSH_HOST:/home/directory/;


# build job will update in the near future
workflows:
  version: 2
  deploy:
    jobs:
      - deploy-production:
          filters:
            branches:
              only:
                - main
  build-and-test:
    when:
      equal: [ dev, $GITHUB_PR_BASE_BRANCH ]
    jobs:
      - deploy-testing
            