# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
orbs:
  ghpr: narrativescience/ghpr@1.1.2
jobs:
  deploy-production:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy over SSH
          command: ssh -p $SSH_PORT $SSH_USERNAME@$SSH_HOST "sh /script/trycd-prod.sh";
  deploy-testing:
    machine:
      enabled: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Deploy over SSH
          command: |
            if [ "$GITHUB_PR_BASE_BRANCH" == "dev" ];
            then
              rsync -vahe 'ssh' -p $SSH_PORT --exclude '.git' --progress ~/app/  $SSH_USERNAME@$SSH_HOST:/home/trycircleci-test;
              ssh -p $SSH_PORT $SSH_USERNAME@$SSH_HOST "sh /script/trycd-test.sh";
            else
              circleci-agent step halt
              exit 0
            fi

# build job will update in the near future
workflows:
  version: 2
  deploy:
    jobs:
      - deploy-production:
          filters:
            branches:
              only:
                - main
  build-and-test:
    jobs:
      - deploy-testing:
          pre-steps:
            - ghpr/get-pr-info
          filters:
            branches:
              ignore:
                - main
