# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
orbs:
  ghpr: narrativescience/ghpr@1.1.2
  node: circleci/node@4.6.0
jobs:
  deploy-production:
    machine:
      enabled: true
    working_directory: ~/app
    steps:
      - checkout
      - run: 
            name: node
            command: |
                curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
                export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
                [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh";
                nvm install --lts
                node -v
      - run:
            name: Deploy over SSH
            command: |
                rsync -vahe "ssh -p $SSH_PORT" --progress ~/app  $SSH_USERNAME@$SSH_HOST:/home;
  deploy-testing:
    machine:
      enabled: true
    working_directory: ~/app
    steps:
      - checkout
      - run: 
            name: node
            command: |
                NVM_DIR="/opt/circleci/.nvm"
                [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"; 
                nvm install --lts
      - run:
            name: Deploy over SSH
            command: |
                rsync -vahe "ssh -p $SSH_PORT" --progress ~/app  $SSH_USERNAME@$SSH_HOST:/home;


# build job will update in the near future
workflows:
  version: 2
  deploy:
    jobs:
      - deploy-production:
          filters:
            branches:
              only:
                - main
  build-and-test:
    jobs:
      - deploy-testing:
          pre-steps:
            - ghpr/get-pr-info
          filters:
            branches:
              ignore:
                - main
